razorpay:
  api:
    key: rzp_test_pCLDOyVPwNuR95
    secret: vlfLLWfX4J1befRc8wTXfZA3
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
spring:
  profiles:
    active: dev
server:
  port: 5454

redis:
  host:localhost
  port:6379
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/twitter
    password: huy111***
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

admin:
  pass: $2a$10$lWYy9R0tP3/xBg0S2Eh40eN5ryfpp269Qh.TBtreobCrVSQxJtWiC

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: student_vzmt_user
    url: jdbc:postgresql://dpg-cmmdabi1hbls73cf9qkg-a.singapore-postgres.render.com/student_vzmt
    password: BzELocsCqi4J0FNQPa86Z6DTpK59Z50r
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect